# this config was migrated from renv.lock on 2026-02-20
[project]
name = "/Users/tladera2/Code/mcr_example_r"
r_version = "4.5"

repositories = [
    { alias = "CRAN", url = "https://cran.rstudio.com/"},
    { alias = "BioCsoft", url = "https://bioconductor.org/packages/3.21/bioc" },
    { alias = "BioCann", url = "https://bioconductor.org/packages/3.21/data/annotation" },
    { alias = "BioCexp", url = "https://bioconductor.org/packages/3.21/data/experiment" },
    { alias = "BioCworkflows", url = "https://bioconductor.org/packages/3.21/workflows" },
    
]

dependencies = [
    { name = "DESeq2", repository = "BioCsoft" },
    { name = "tidySummarizedExperiment", repository = "BioCsoft" },
    { name = "BH", repository = "CRAN" },
    { name = "BiocManager", repository = "CRAN" },
    { name = "R6", repository = "CRAN" },
    { name = "RColorBrewer", repository = "CRAN" },
    { name = "Rcpp", repository = "CRAN" },
    { name = "RcppArmadillo", repository = "CRAN" },
    { name = "S7", repository = "CRAN" },
    { name = "abind", repository = "CRAN" },
    { name = "askpass", repository = "CRAN" },
    { name = "base64enc", repository = "CRAN" },
    { name = "bslib", repository = "CRAN" },
    { name = "cachem", repository = "CRAN" },
    { name = "cli", repository = "CRAN" },
    { name = "cpp11", repository = "CRAN" },
    { name = "crayon", repository = "CRAN" },
    { name = "crosstalk", repository = "CRAN" },
    { name = "curl", repository = "CRAN" },
    { name = "data.table", repository = "CRAN" },
    { name = "digest", repository = "CRAN" },
    { name = "dplyr", repository = "CRAN" },
    { name = "ellipsis", repository = "CRAN" },
    { name = "evaluate", repository = "CRAN" },
    { name = "fansi", repository = "CRAN" },
    { name = "farver", repository = "CRAN" },
    { name = "fastmap", repository = "CRAN" },
    { name = "fontawesome", repository = "CRAN" },
    { name = "formatR", repository = "CRAN" },
    { name = "fs", repository = "CRAN" },
    { name = "futile.logger", repository = "CRAN" },
    { name = "futile.options", repository = "CRAN" },
    { name = "generics", repository = "CRAN" },
    { name = "ggplot2", repository = "CRAN" },
    { name = "glue", repository = "CRAN" },
    { name = "gtable", repository = "CRAN" },
    { name = "highr", repository = "CRAN" },
    { name = "htmltools", repository = "CRAN" },
    { name = "htmlwidgets", repository = "CRAN" },
    { name = "isoband", repository = "CRAN" },
    { name = "jquerylib", repository = "CRAN" },
    { name = "jsonlite", repository = "CRAN" },
    { name = "knitr", repository = "CRAN" },
    { name = "labeling", repository = "CRAN" },
    { name = "lambda.r", repository = "CRAN" },
    { name = "lazyeval", repository = "CRAN" },
    { name = "lifecycle", repository = "CRAN" },
    { name = "locfit", repository = "CRAN" },
    { name = "magrittr", repository = "CRAN" },
    { name = "matrixStats", repository = "CRAN" },
    { name = "memoise", repository = "CRAN" },
    { name = "mime", repository = "CRAN" },
    { name = "openssl", repository = "CRAN" },
    { name = "otel", repository = "CRAN" },
    { name = "patchwork", repository = "CRAN" },
    { name = "pillar", repository = "CRAN" },
    { name = "pkgconfig", repository = "CRAN" },
    { name = "plotly", repository = "CRAN" },
    { name = "promises", repository = "CRAN" },
    { name = "purrr", repository = "CRAN" },
    { name = "rappdirs", repository = "CRAN" },
    { name = "rlang", repository = "CRAN" },
    { name = "rmarkdown", repository = "CRAN" },
    { name = "sass", repository = "CRAN" },
    { name = "scales", repository = "CRAN" },
    { name = "snow", repository = "CRAN" },
    { name = "stringi", repository = "CRAN" },
    { name = "stringr", repository = "CRAN" },
    { name = "sys", repository = "CRAN" },
    { name = "tibble", repository = "CRAN" },
    { name = "tidyr", repository = "CRAN" },
    { name = "tidyselect", repository = "CRAN" },
    { name = "tinytex", repository = "CRAN" },
    { name = "ttservice", repository = "CRAN" },
    { name = "utf8", repository = "CRAN" },
    { name = "vctrs", repository = "CRAN" },
    { name = "viridisLite", repository = "CRAN" },
    { name = "withr", repository = "CRAN" },
    { name = "xfun", repository = "CRAN" },
    { name = "yaml", repository = "CRAN" }
]
